language: cpp

compiler:
- gcc
- clan

script:
- cmake -Hformatter_lib/ -Bformatter_lib/_build
- cmake -Hformatter_ex_lib/ -Bformatter_ex_lib/_build
- cmake -Hhello_world_application -Bhello_world_application/_build
- cmake -Hsolver_lib -Bsolver_lib/_build
- cmake -Hsolver_application -Bsolver_application/_build

addons:
apt:
sources:
- ubuntu-toolchain-r-test
- llvm-toolchain-precise-3.6
packages:
- g++-7
- clang-3.6
